### PR TITLE
Add initial PyLint RC files (copied from Sorbic)

### PR DESCRIPTION
**Pull request by s0undt3ch**
@SmithSamuelM per request of @thatch45 for the new Jenkins server...

[Review on Reviewable](https://reviewable.io/reviews/saltstack/raet/42)

### CODE REVIEW

**Comment by s0undt3ch** [comment]
Go Go Jenkins!

**Comment by s0undt3ch** [comment]
Go Go Jenkins!

**Comment by s0undt3ch** [comment]
@SmithSamuelM I think this is ready for another review from you.

**Comment by thatch45** [comment]
@s0undt3ch can you please rebase? Then I will merge this in

**Comment by s0undt3ch** [comment]
Will do.

**Comment by s0undt3ch** [comment]
Rebased.

**Comment by thatch45** [comment]
Thanks @s0undt3ch !

**Comment by s0undt3ch** [comment]
There are some more lint issues. Cleaning up.

**Comment by thatch45** [comment]
I am not surprised :)

**Comment by s0undt3ch** [comment]
It passes!

**Pull request merged**
