### PR TITLE
Update raet include fixes since last release update version update for ioflo changes

### PR DESCRIPTION
**Pull request by SmithSamuelM**
This pull request includes a bunch of small changes made over the last while. Some to accommodate
changes in the ioflo api for future compatibility. Some changes to deal with simplejson vs json  in python3

### CODE REVIEW

**Comment by jfindlay** [comment]
@SmithSamuelM, did you intend to include some commits from @DmitryKuzmenko?

@thatch45 and/or @DmitryKuzmenko, please review.

**Comment by SmithSamuelM** [comment]
I am not sure. But I fetched the latest from saltraet and then merged with mine. So its almost like they were orphaned or something.
I guess a diff might reveal if they are unique or just a git cherry pick artifact

**Comment by DmitryKuzmenko** [comment]
Looks good for me. Thank you @SmithSamuelM !

**Comment by thatch45** [comment]
Thanks @SmithSamuelM !!

**Pull request merged**
