### PR TITLE
Stale messages logic change

### PR DESCRIPTION
**Pull request by DmitryKuzmenko**
Don't nack transaction if 1st try lost all message segments:
	- keep done messengent transactions IDs for limited time
	- accept message segment if the tid is known as done
Unit test also added.

### CODE REVIEW

**Comment by thatch45** [comment]
Aweaome!! Thanks

**Comment by SmithSamuelM** [comment]
Could you explain in more detail what the error was.  Its seems inelegant to have to keep around old transactions for some time period. I wonder if the previous change is related to this one or introduced this one.   It should be  that if all the first burst of segments are dropped that the messenger just resends after it times out waiting for an ack.

**Comment by SmithSamuelM** [comment]
I submitted a pull request which I believe fixes the problem without having to keep old transactions around.

https://github.com/saltstack/raet/pull/58

**Comment by DmitryKuzmenko** [comment]
@SmithSamuelM Thank you for taking care of this. I've added a comment there, in #58.
Actually I dislike the idea of keeping done transactions by timeout, but for now I have no better idea how to don't loose and don't duplicate messages without acknowledging each packet (segment).

**Comment by SmithSamuelM** [comment]
One of the problems with duplicate packet detection is that any timeout based scheme does not guarantee no duplicates. A UDP packet could be held in a network buffer someplace on the internet for an indefinitely long time. This means that A duplicate transaction could be started that exceeded the timeout.  So the question is? Is duplicate packet detection an absolute never ever, or just most of the time.  Within a transaction, since the receiver keeps a list of all the packet segment numbers the duplicate is absolute. But currently there is a possibility that a message gets sent more than once. This is something to confirm with Tom but as I understand it, Salt does not rely on absolute guarantees that a message or event is not ever duplicated. Ie Salt commands are idempotent.  If absolute duplicate message detection is required then the one reasonable way to do that is to have a monotonic transaction id escrow within each session on the Messegent. This is better than keeping the transaction around as it lighter weight. A nack so the Messegent can indicate to the Messenger that the TID is stale is needed so to that the Messenger can retry with a later TID.  Basically the Messegent keeps a list of used TIDs in escrow with a timeout There is a minimum TID in escrow. Any new transactions with TIDs lower than the minimum are invalid and will be nacked. As old TIDs expire a new higher minimum is created. This allows for out of order TID to still work since the messages are Asnyc. But imposes a time window the valid IDs.  There is also TID rollover logic.  But check with Tom on the duplicate message constraint.

**Comment by SmithSamuelM** [comment]
But even the proposed scheme does not absolutely guarantee that a duplicate message cannot be sent
because of TID rollover. It just makes it very unlikely. So the real question is how unlikely does it need to be? The only way to guarantee no duplicates is to have infinite memory.

**Comment by SmithSamuelM** [comment]
If I remember correctly, the decision was that Salt tolerates duplicate messages because of the JID. So RAET can be async. Which means the two test cases where a duplicate message is sent are valid conditions and are not errors.   Its more important that the message transactions be lively (that is complete) than not duplicated. As a compromise liveness is preferred which is how it works now. The fix I posted fixes a liveness problem (when all the segments are dropped) but then allows for duplicates.

**Comment by DmitryKuzmenko** [comment]
@SmithSamuelM thank you for detailed explanation. If duplication is OK for raet, I'd update the load test to treat dups as not errors. @thatch45 what would you say about this?

**Comment by thatch45** [comment]
I would say that dupes are not errors only if we retain reliability, I was under the impression that we had packets that were not making it across. Also, we have seen the problem in salt-raet where salt does not handle duplication and so a single minion will register as returning many times, this causes issues with the master assuming that duplicate commands are sent. I would rather mitigate duplicates if it is possible.
The problem is also that not all network data is gated by jids

**Comment by SmithSamuelM** [comment]
The error I fixed was a liveness (reliability) issue where a message would not make it across. that is fixed.

What remains is that in a couple of corner cases a duplicate will be sent. The corner cases both result in a duplicate message when the initial segments get across successfully but the done ack gets lost.
The receiver completes the transaction and removes it. The redo from the sender then looks like a new transaction. Especially in the case where the message is one segment long, that single packet could be in a network buffer for an indeterminate time somewhere on the internet, which means it would be very difficult to prevent it.    But the rate at which duplicates occur can be reduced by keeping some record of completed transaction ids. It would useful to understand what messages types are not gated by JID or have now application layer identifier that could be used to prevent duplicates to see how often these corner cases would occur and what the fix should be.  Its easier to fix at the application layer by adding a unique message identifier like the JID for those messages that don't have a JID.

In contrast an Application layer message id could be long enough (as in GUID long with timestamp like JID) to effectively never roll over since the message id is only sent once in a message not once per segment. 

A transport layer RAET header with Transaction ID (fid) is sent with every segment so the length of the TID must be small which means it rolls over. 

In both cases a form a duplicate detection can be implemented, its just less effective and more work to do it at the transport layer.  Whereas adding a filter that throws away duplicate messages based on unique monotonic message ids is more effective and the same or less work.

**Comment by SmithSamuelM** [comment]
An application layer message id filter can be called by the salt road router upon reception. before it routes the message to another lane or share.

**Comment by SmithSamuelM** [comment]
If the message id's include time stamps, then it would be trivial to have a buffer of received message ids that once its full, the oldest message ids are deleted. The filter then compares each received message id for a matching one in the buffer and if found drops the new one as a duplicate. If not found appends the new one to the buffer.   this can be used with JIDs as well. And events. as events also have event ids that are time stamped. So an outgoing filter can be created that the router runs that injects a message id into any message that does not have a jid or event id.

**Comment by SmithSamuelM** [comment]
The only requirement is that all IDs are globally unique and include a time stamp portion. 
One could have a buffer per remote  if needed.

**Pull request merged**
